---
server:
  port: 8080

application:
    version: 1.0


keycloak:
    host: ${KEYCLOAK_HOST:http://localhost:8080}
    auth-server-url: ${keycloak.host}/auth
    realm: test
    resource: helloworld


security:
  oauth2:
    client:
      clientId: ${keycloak.resource}
    resource:
      userInfoUri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/userinfo
      token-type: Bearer
      jwk:
        key-set-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/certs


swagger:
    title: Hello World Service
    description: The REST API documentation for the Hello World Service
    version: 1.0.0
    termsOfServiceUrl:
    contactName: Yusuf Kör
    contactUrl: https://github.com/ykoer
    contactEmail: yusuf.koer@googlemail.com
    license:
    licenseUrl:




